#!/usr/bin/env bash
# =============================================================================
# ExpenseFlow — Production Deploy Script
# Usage: bash deploy.sh [branch] [--rollback]
# =============================================================================
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
BRANCH="${1:-main}"
APP_DIR="/var/www/expenseflow"
REPO_DIR="${APP_DIR}/repo"
RELEASES_DIR="${APP_DIR}/releases"
SHARED_DIR="${APP_DIR}/shared"
CURRENT_LINK="${APP_DIR}/current"
KEEP_RELEASES=5
PHP="${PHP_BIN:-php8.3}"
COMPOSER="${COMPOSER_BIN:-/usr/local/bin/composer}"
TIMESTAMP=$(date +%Y%m%d%H%M%S)
RELEASE_DIR="${RELEASES_DIR}/${TIMESTAMP}"
SUPERVISOR_CONF="/etc/supervisor/conf.d/expenseflow-worker.conf"
SUPERVISOR_GROUP="expenseflow-worker"

# ── Logging ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

_ts()      { date '+%Y-%m-%d %H:%M:%S'; }
log_info() { echo -e "${BLUE}$(_ts) [INFO]${NC}    $*"; }
log_ok()   { echo -e "${GREEN}$(_ts) [SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}$(_ts) [WARN]${NC}    $*" >&2; }
log_err()  { echo -e "${RED}$(_ts) [ERROR]${NC}   $*" >&2; }
die()      { log_err "$*"; exit 1; }
step()     { echo -e "\n${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"; \
             echo -e "${CYAN}${BOLD}  ▶  $*${NC}"; \
             echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"; }

# ── Helper: safe sudo ─────────────────────────────────────────────────────────
# Runs a command with sudo only if not already root.
safe_sudo() {
    if [[ $EUID -eq 0 ]]; then
        "$@"
    else
        sudo "$@"
    fi
}

# ── Helper: auto-detect php-fpm service ──────────────────────────────────────
detect_phpfpm_service() {
    # Try versioned names first, then generic
    local candidates=("php8.3-fpm" "php8.2-fpm" "php8.1-fpm" "php8.0-fpm" "php-fpm")
    for svc in "${candidates[@]}"; do
        if systemctl list-units --type=service --all 2>/dev/null | grep -q "^  ${svc}.service"; then
            echo "${svc}"
            return
        fi
    done
    # Fallback: derive from PHP binary version
    if command -v "${PHP}" &>/dev/null; then
        local ver
        ver=$("${PHP}" -r "echo PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;")
        echo "php${ver}-fpm"
        return
    fi
    echo ""
}

# ── Helper: reload php-fpm safely ────────────────────────────────────────────
reload_phpfpm() {
    local svc
    svc=$(detect_phpfpm_service)
    if [[ -z "${svc}" ]]; then
        log_warn "Could not detect php-fpm service — skip reload"
        return
    fi
    if systemctl is-active --quiet "${svc}" 2>/dev/null; then
        safe_sudo systemctl reload "${svc}" \
            && log_ok "php-fpm reloaded (${svc})" \
            || log_warn "php-fpm reload failed (${svc}) — workers may use stale opcache"
    else
        log_warn "php-fpm (${svc}) not active — skip reload"
    fi
}

# ── Helper: reload nginx safely ───────────────────────────────────────────────
reload_nginx() {
    if ! command -v nginx &>/dev/null; then
        log_warn "nginx not installed — skip reload"
        return
    fi
    if ! systemctl is-active --quiet nginx 2>/dev/null; then
        log_warn "nginx not running — skip reload"
        return
    fi
    if nginx -t -q 2>/dev/null; then
        safe_sudo systemctl reload nginx \
            && log_ok "nginx reloaded" \
            || log_warn "nginx reload failed — check nginx logs"
    else
        log_warn "nginx config test failed — skip reload to avoid outage"
    fi
}

# ── Helper: ensure supervisor worker config ───────────────────────────────────
ensure_supervisor_conf() {
    if [[ -f "${SUPERVISOR_CONF}" ]]; then
        return
    fi
    log_warn "Supervisor config missing at ${SUPERVISOR_CONF} — creating it"

    # Determine the artisan path via current symlink (may not exist yet on first deploy)
    local artisan_path="${CURRENT_LINK}/artisan"
    local log_path="${SHARED_DIR}/storage/logs/worker.log"

    safe_sudo tee "${SUPERVISOR_CONF}" > /dev/null << SVCONF
; ExpenseFlow queue worker — auto-generated by deploy.sh
; Edit manually if you need custom settings, then run:
;   sudo supervisorctl reread && sudo supervisorctl update

[group:${SUPERVISOR_GROUP}]
programs=${SUPERVISOR_GROUP}-1,${SUPERVISOR_GROUP}-2

[program:${SUPERVISOR_GROUP}-1]
process_name=%(program_name)s_%(process_num)02d
command=${PHP} ${artisan_path} queue:work --queue=mail,default --sleep=3 --tries=3 --max-time=3600 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=${log_path}
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopwaitsecs=3600
startsecs=3

[program:${SUPERVISOR_GROUP}-2]
process_name=%(program_name)s_%(process_num)02d
command=${PHP} ${artisan_path} queue:work --queue=default --sleep=3 --tries=3 --max-time=3600 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=${log_path}
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopwaitsecs=3600
startsecs=3
SVCONF
    log_ok "Supervisor config written: ${SUPERVISOR_CONF}"
}

# ── Helper: restart supervisor workers safely ─────────────────────────────────
restart_workers() {
    # 1. supervisorctl must exist
    if ! command -v supervisorctl &>/dev/null; then
        log_warn "supervisorctl not installed — skip worker restart"
        return
    fi

    # 2. supervisor service must be running
    if ! systemctl is-active --quiet supervisor 2>/dev/null; then
        log_warn "supervisor service not running — attempting start"
        safe_sudo systemctl start supervisor 2>/dev/null \
            || { log_warn "Could not start supervisor — skip worker restart"; return; }
    fi

    # 3. Ensure config exists (creates if missing)
    ensure_supervisor_conf

    # 4. Reread + update so new/changed configs are loaded
    safe_sudo supervisorctl reread 2>/dev/null  || log_warn "supervisorctl reread failed"
    safe_sudo supervisorctl update 2>/dev/null  || log_warn "supervisorctl update failed"

    # 5. Restart — try group first, then individual programs, then warn
    if safe_sudo supervisorctl status "${SUPERVISOR_GROUP}:" &>/dev/null 2>&1; then
        safe_sudo supervisorctl restart "${SUPERVISOR_GROUP}:" \
            && log_ok "Queue workers restarted (group: ${SUPERVISOR_GROUP})" \
            && return
    fi

    # Try restarting individual programs in the group
    local restarted=0
    while IFS= read -r prog; do
        if safe_sudo supervisorctl restart "${prog}" &>/dev/null 2>&1; then
            log_ok "Restarted worker: ${prog}"
            restarted=1
        fi
    done < <(safe_sudo supervisorctl status 2>/dev/null | grep "${SUPERVISOR_GROUP}" | awk '{print $1}')

    if [[ $restarted -eq 0 ]]; then
        log_warn "Could not restart workers — supervisor may need manual intervention"
        log_warn "Run: sudo supervisorctl status"
    fi
}

# ── Rollback ──────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--rollback" ]]; then
    step "ROLLBACK"
    mapfile -t RELEASES < <(ls -1dt "${RELEASES_DIR}"/*/  2>/dev/null | head -5)
    if [[ ${#RELEASES[@]} -lt 2 ]]; then
        die "No previous release to roll back to."
    fi
    PREV="${RELEASES[1]%/}"
    CURRENT_REL=$(readlink -f "${CURRENT_LINK}" 2>/dev/null || echo "none")
    log_info "Current:  ${CURRENT_REL}"
    log_info "Previous: ${PREV}"
    ln -sfn "${PREV}" "${CURRENT_LINK}"
    reload_phpfpm
    reload_nginx
    restart_workers
    log_ok "Rolled back to: $(basename "${PREV}")"
    exit 0
fi

# ── Pre-deploy checks ─────────────────────────────────────────────────────────
step "Pre-deploy checks"

CHECKS_FAILED=0

_check() {
    local desc="$1"; shift
    if "$@" &>/dev/null; then
        log_ok "  ✓ ${desc}"
    else
        log_err "  ✗ ${desc}"
        CHECKS_FAILED=1
    fi
}

_check "PHP installed (${PHP})"         command -v "${PHP}"
_check "Composer installed"             command -v "${COMPOSER}"
_check "Node.js installed"              command -v node
_check "App directory exists"           test -d "${APP_DIR}"
_check "Bare repo exists"               test -d "${REPO_DIR}"
_check ".env exists"                    test -f "${SHARED_DIR}/.env"
_check "storage/ writable"             test -w "${SHARED_DIR}/storage"

# bootstrap/cache check — may not exist yet on very first deploy
if [[ -d "${CURRENT_LINK}/bootstrap/cache" ]]; then
    _check "bootstrap/cache writable"   test -w "${CURRENT_LINK}/bootstrap/cache"
else
    log_warn "  ~ bootstrap/cache not checked (no current release yet)"
fi

# DB connectivity — source .env to get DB vars (non-fatal)
if [[ -f "${SHARED_DIR}/.env" ]]; then
    DB_HOST=$(grep -E '^DB_HOST='     "${SHARED_DIR}/.env" | cut -d= -f2 | tr -d '"' | tr -d "'") || true
    DB_PORT=$(grep -E '^DB_PORT='     "${SHARED_DIR}/.env" | cut -d= -f2 | tr -d '"' | tr -d "'") || true
    DB_CONNECTION=$(grep -E '^DB_CONNECTION=' "${SHARED_DIR}/.env" | cut -d= -f2 | tr -d '"' | tr -d "'") || true
    DB_HOST="${DB_HOST:-127.0.0.1}"
    DB_PORT="${DB_PORT:-5432}"
    if command -v nc &>/dev/null; then
        if nc -z -w3 "${DB_HOST}" "${DB_PORT}" 2>/dev/null; then
            log_ok "  ✓ Database reachable (${DB_HOST}:${DB_PORT})"
        else
            log_warn "  ~ Database unreachable at ${DB_HOST}:${DB_PORT} — check DB_HOST/DB_PORT in .env"
        fi
    else
        log_warn "  ~ nc not available — skipping DB connectivity check"
    fi
fi

if [[ ${CHECKS_FAILED} -ne 0 ]]; then
    die "Pre-deploy checks failed — fix above errors before deploying"
fi

log_ok "All pre-deploy checks passed"

# ── Fetch latest code ──────────────────────────────────────────────────────────
step "Fetching code (branch: ${BRANCH})"
git -C "${REPO_DIR}" fetch --all --prune
COMMIT=$(git -C "${REPO_DIR}" rev-parse "origin/${BRANCH}")
log_info "Deploying commit: ${COMMIT}"

# ── Create release directory ───────────────────────────────────────────────────
step "Creating release: ${TIMESTAMP}"
mkdir -p "${RELEASE_DIR}"
git -C "${REPO_DIR}" --work-tree="${RELEASE_DIR}" checkout -f "origin/${BRANCH}"
log_ok "Code checked out to ${RELEASE_DIR}"

# ── Symlink shared files/dirs ──────────────────────────────────────────────────
step "Linking shared resources"
rm -rf "${RELEASE_DIR}/storage"
ln -sfn "${SHARED_DIR}/storage"        "${RELEASE_DIR}/storage"
ln -sfn "${SHARED_DIR}/public/storage" "${RELEASE_DIR}/public/storage"
ln -sfn "${SHARED_DIR}/.env"           "${RELEASE_DIR}/.env"
log_ok "Shared links created"

# Ensure bootstrap/cache exists and is writable in new release
mkdir -p "${RELEASE_DIR}/bootstrap/cache"
chmod -R 775 "${RELEASE_DIR}/bootstrap/cache"

# ── PHP dependencies ──────────────────────────────────────────────────────────
step "Installing Composer dependencies"
"${PHP}" "${COMPOSER}" install \
    --no-dev \
    --optimize-autoloader \
    --no-interaction \
    --prefer-dist \
    --working-dir="${RELEASE_DIR}"
log_ok "Composer done"

# ── Frontend assets ───────────────────────────────────────────────────────────
step "Building frontend assets"
if [[ -f "${RELEASE_DIR}/package.json" ]]; then
    cd "${RELEASE_DIR}"
    export NODE_OPTIONS=--max-old-space-size=512
    npm ci
    npm run build
    # Abort deploy if manifest is missing — silent OOM-kill leaves no manifest
    if [[ ! -f "${RELEASE_DIR}/public/build/manifest.json" ]]; then
        log_warn "Frontend build failed: public/build/manifest.json not found. Aborting deploy."
        exit 1
    fi
    cd - >/dev/null
    log_ok "Frontend build done"
else
    log_warn "No package.json found — skipping frontend build"
fi

# ── Maintenance mode ON ────────────────────────────────────────────────────────
step "Enabling maintenance mode"
CURRENT_ACTIVE=$(readlink -f "${CURRENT_LINK}" 2>/dev/null || echo "")
if [[ -n "${CURRENT_ACTIVE}" && -d "${CURRENT_ACTIVE}" ]]; then
    "${PHP}" "${CURRENT_ACTIVE}/artisan" down \
        --render="errors.503" \
        --retry=30 \
        --refresh=15 \
        --secret="$(openssl rand -hex 16)" \
        2>/dev/null || log_warn "Could not enable maintenance mode on current release"
else
    log_info "No current release — skipping maintenance mode"
fi

# ── Database migrations ────────────────────────────────────────────────────────
step "Running migrations"
"${PHP}" "${RELEASE_DIR}/artisan" migrate --force --no-interaction
log_ok "Migrations complete"

# ── Activate release (atomic symlink swap) ────────────────────────────────────
step "Activating release"
ln -sfn "${RELEASE_DIR}" "${CURRENT_LINK}"
log_ok "Current → ${TIMESTAMP}"

# ── Laravel optimizations ──────────────────────────────────────────────────────
step "Running post-deploy optimizations"
ARTISAN="${PHP} ${CURRENT_LINK}/artisan"

${ARTISAN} storage:link       2>/dev/null || true
${ARTISAN} config:cache       && log_ok "Config cached"
${ARTISAN} route:cache        && log_ok "Routes cached"
${ARTISAN} view:cache         && log_ok "Views cached"
${ARTISAN} event:cache        && log_ok "Events cached"
${ARTISAN} icons:cache        2>/dev/null || true   # blade-icons if installed

# ── Maintenance mode OFF ───────────────────────────────────────────────────────
step "Disabling maintenance mode"
${ARTISAN} up
log_ok "Application online"

# ── Set permissions ───────────────────────────────────────────────────────────
step "Setting permissions"
chmod -R 775 "${SHARED_DIR}/storage"
chmod -R 775 "${RELEASE_DIR}/bootstrap/cache"
chown -R www-data:www-data "${SHARED_DIR}/storage"     2>/dev/null || \
    log_warn "Could not chown storage — run manually if needed"
chown -R www-data:www-data "${RELEASE_DIR}/bootstrap/cache" 2>/dev/null || true
log_ok "Permissions set"

# ── Reload services ───────────────────────────────────────────────────────────
step "Reloading services"
reload_phpfpm
reload_nginx
restart_workers

# ── Prune old releases ────────────────────────────────────────────────────────
step "Pruning old releases (keeping ${KEEP_RELEASES})"
mapfile -t RELEASES_ALL < <(ls -1dt "${RELEASES_DIR}"/*/  2>/dev/null)
RELEASES_COUNT=${#RELEASES_ALL[@]}
if [[ ${RELEASES_COUNT} -gt ${KEEP_RELEASES} ]]; then
    TO_DELETE=("${RELEASES_ALL[@]:${KEEP_RELEASES}}")
    for OLD in "${TO_DELETE[@]}"; do
        log_info "Removing: ${OLD%/}"
        rm -rf "${OLD%/}"
    done
fi
log_ok "Kept ${KEEP_RELEASES} most recent releases"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║       DEPLOYMENT SUCCESSFUL          ║${NC}"
echo -e "${GREEN}${BOLD}╠══════════════════════════════════════╣${NC}"
echo -e "${GREEN}${BOLD}║${NC}  Release : ${TIMESTAMP}          ${GREEN}${BOLD}║${NC}"
echo -e "${GREEN}${BOLD}║${NC}  Commit  : ${COMMIT:0:12}                    ${GREEN}${BOLD}║${NC}"
echo -e "${GREEN}${BOLD}║${NC}  Branch  : ${BRANCH}                    ${GREEN}${BOLD}║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════╝${NC}"
